version: "3.9"
name: lgtm-generator

services:
  app:
    container_name: lgtm-generator-app
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    image: lgtm-generator-with-emoji:latest
    volumes:
      - ../:/app
    # ports:
    #   - "9090:9090"

  web:
    container_name: lgtm-generator-web
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - app
      - db
    volumes:
      - ../:/app

  db:
    container_name: lgtm-generator-db
    platform: linux/x86_64 # m1 mac でのエラー対策
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lgtm-generator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - /var/lib/docker/volumes/

  minio:
    container_name: lgtm-generator-minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "miniouser"
      MINIO_ROOT_PASSWORD: "miniopassword"
    command: server /data --console-address ":9001"
    volumes:
      - ./.docker/minio/data:/data

# volumes:
#    mysql-volume:
